name: Advanced CI 
on:
  push:

env:
  APP_NAME: myapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $APP_NAME
      - run: echo ${{ secrets.MY_PASSWORD }}
      - run: docker build -t myapp .
      - run: echo "hello artifact" > report.txt
      - uses: actions/upload-artifact@v4
        with:
           name: myreport
           path: report.txt
